### ISSUE TITLE
example

### ISSUE THREAD

**Issue by FPeter84** [csdexter/RDSDecoder#1]
Hello! First of all, thanks for Your efforts! Do You have an example, how to initialize this library then decode the 4 word block coming from RDS receiver?

**Comment by csdexter** [comment]
Hello and thanks for your comment.

I've added a basic example in edcacf71e3d8ca7f85ab7af1d6f115e53e1da166, I hope it helps. If there's anything in particular you'd like to see shown in an further example, please let me know.
